--- 
abstract: FastCGI daemon start/stop script for using FastCgiExternalServer
author: Naoya Sano <sano@naoya.net>
distribution_type: module
generated_by: Module::Install version 0.650
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Catalyst-Helper-FastCGI-ExternalServer
no_index: 
  directory: 
    - inc
    - t
requires: 
  Catalyst: 0
  Catalyst::Utils: 0
  Cwd: 0
  DateTime: 0
  FCGI: 0
  FCGI::ProcManager: 0
  File::Spec: 0
  Getopt::Long: 0
version: 0.05
